// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FBWeb.Models
{
    public partial class ContactTable
    {
        [Key]
        [Column("contact_id")]
        public int ContactId { get; set; }
        [Column("name")]
        [StringLength(100)]
        public string Name { get; set; }
        [Column("imgUrl")]
        [StringLength(250)]
        public string ImgUrl { get; set; }
        [Column("phone")]
        public int? Phone { get; set; }
        [Column("user_id")]
        public int? UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("ContactTable")]
        public virtual User User { get; set; }
    }
}