// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FBWeb.Models
{
    public partial class TaskTable
    {
        [Key]
        [Column("task_id")]
        public int TaskId { get; set; }
        [Column("textTask")]
        [StringLength(250)]
        public string TextTask { get; set; }
        [Column("dateTask", TypeName = "date")]
        public DateTime? DateTask { get; set; }
        [Column("completeTask")]
        public int CompleteTask { get; set; }
        [Column("user_id")]
        public int UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("TaskTable")]
        public virtual User User { get; set; }
    }
}