// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FBWeb.Models
{
    public partial class User
    {
        public User()
        {
            ContactTable = new HashSet<ContactTable>();
            EventTable = new HashSet<EventTable>();
            NoteTable = new HashSet<NoteTable>();
            TaskTable = new HashSet<TaskTable>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("user_name")]
        [StringLength(80)]
        public string UserName { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<ContactTable> ContactTable { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<EventTable> EventTable { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<NoteTable> NoteTable { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<TaskTable> TaskTable { get; set; }
    }
}